### ISSUE TITLE
Bot is not banning users or typing in the log channel

### ISSUE THREAD

**Issue by mrhappyma** [AyuAi/beemo-docs#22]
Bot has admin permissions

**Comment by wasdennnoch** [comment]
This repo is for Beemo's documentation; for support I suggest you ask in the Beemo Support server: https://beemo.gg/discord.

**Comment by mrhappyma** [comment]
@wasdennnoch I can't ask in the support server, I don't have a phone to verify.

**Comment by wasdennnoch** [comment]
If you DM Ayu or tell me your username we can give you a role to bypass it ^^
